### PR TITLE
feat: integration specs for views

### PR DESCRIPTION
**Pull request by taher-software**
In this branch, we've made the following tests: 
- test for login page behaviors and functionalities.
- test for User index page behaviors and functionalities.
- test for user show page behaviors and functionalities.
- test User post index page behaviors and functionalities.
- test Post show page behaviors and functionalities.

Please run 'rspec spec/integration/'  to check the  new required tests.

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi @Taher-web-dev, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Some of your tests are failing.  from what I can see, some of them require data from the database, and I don't have them and so do any other who would try to test your PR. 
  Screen Shot 2022-03-03 at 03 41 13
If that's the only case, you could try to put some seeds in your seed file and remember to add instructions on how to run seeds.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by taher-software** [comment]
> Hi @Taher-web-dev,
> 
> _Great job so far clap 100 +1. However, there are few issues we need to address before we move on. Please, check the comments below._
> 
> ## Highlights
> * Follows git workflow.  100
> * Codebase looks clean and professional. 100
> 
> ## Required Changes 
> * [ ]  Some of your tests are failing.  from what I can see, some of them require data from the database, and I don't have them and so do any other who would try to test your PR.
>   Screen Shot 2022-03-03 at 03 41 13
>   If that's the only case, you could try to put some seeds in your seed file and remember to add instructions on how to run seeds.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * [ ]  Check the comments under the review.
> 
> Cheers and Happy coding!clapclapclap
> 
> **Feel free to leave any questions or comments in the PR thread if something is not 100% clear.**
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> > As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by taher-software** [comment]
Hi @rukundoeric 
It seems like you had run all the test in my spec folder.But some of them are obsolete now , I have used in the beginning of the application. Besides, it seems like you miss webdrivers in your laptop, the message already that you had sent already mention that in the bottom. Please run 'rspec spec/integration/' and everything will work fain.

**Review by elyor-doniyorov — COMMENTED** [review]
Hi @Taher-web-dev, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with an already closed Pull Request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by t-yanick — APPROVED** [review]
Hi @Taher-web-dev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
